### ISSUE TITLE
IKEA Trådfri Transformer 10W only works twice

### ISSUE THREAD

**Issue by boreno** [athombv/com.ikea.tradfri#47]
I can control my 2 transformers a couple of times only, then I need to reboot the homey for it to start working again. Restarting the app does not work.

I am testing using a home automation in HomeKit through HomeyKit. All items are controlled correctly except for my two transformers, that work the first time, and the second time they react more slowly, and the third time not at all. At that point I can't control them from the Homey application on Mac either. Restarting the micro controller doesn't help, but restarting the Homey does.

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.

In the meantime, have you tried restarting the com.ikea.tradfri app on Homey instead of rebooting Homey itself?

**Comment by boreno** [comment]
I have now filed an issue at the link you suggested. Restarting the app
does not help. I believe it is a problem that occur when two IKEA Trådfri
10W devices are being controlled simultaneously through the HomeyKit app in
an iOS HomeKit automation. I have specified all info in the new report.
