### ISSUE TITLE
Update capability value on power off/on

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.ikea.tradfri#7]
My lights are behind normal main switches. Advantage is that I can turn them off and on with the mains or with Homey. However, after having them turned off and on with the main switch they don't show as "on" in Homey. Don't know if the status can be polled?

**Comment by RobinBol** [comment]
How come the devices show as off in Homey after toggling them via mains? The bulbs could be polled in theory, but it is not really desired.

**Comment by RobinBol** [comment]
@bvdbos do you have some more information for me? The lights should not reflect whether they are powered or not currently.

**Comment by bvdbos** [comment]
1) turned the lights off with main power. They still show as "on" in the Homey UI
2) turned the lights off in Homey UI. Turned on the lights with main power. They still show as off in Homey...

**Comment by fredrikj83** [comment]
I have a similar request. Sometimes after powering on a device from the app, it will show as powered on even if it failed (maybe due to bad signal between Homey and the light bulb). I think the same applies if I try to put a device "ON" but it has no power (might be powered off via main power switch).

I have not investigated this much, but I think that the correct state is showing if the device is powered on from a Flow. Then lights that were not powered on for some reason show ass OFF in the app.

**Comment by Kingcool88** [comment]
Im trying to use Trådfri to react when the power is shut off.
The thing is that i want to build a flow that triggers when i switch off and on the wall switch that control the Trådfri bulb. In this wall switch i have mounted a feather that when pressed, flip the switch back to on. But after one press on the button i want to trigger the bulb off, and after the next press i want it to trigger the bulb on. 
This way, i can control Trådfri with Homey all the time (because the switch always goes back to on then pressed), and at the same time switch the bulb on and off with the wall switch.
So if we can read the on/off status of the bulb correctly, this could be very usefull! So im hoping for a solution soon!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2566
