### ISSUE TITLE
Ikea E14 color/rgb bulb (LED1624G9)

### ISSUE THREAD

**Issue by Frudy** [athombv/com.ikea.tradfri#75]
Please add support for the Ikea E14 color/rgb bulb (LED1624G9)

**Comment by TerryBouhuizen** [comment]
Same request here! Tradfri LED 600 lm 8.6 W E14 LED1624G9 Color RGB Dimable.
Thanks in advance!

**Comment by RobinBol** [comment]
Hi! Could you add the device to Homey (as unknown ZigBee device) and then send me the node information (device settings > advanced > product ID/device ID/profile ID)?

**Comment by TerryBouhuizen** [comment]
Will this work? 
    	
    	

    	Outlook voor iOS downloaden
    
  



On Mon, Sep 2, 2019 at 9:51 AM +0200, "Robin Bolscher" <notifications@github.com> wrote:












Hi! Could you add the device to Homey (as unknown ZigBee device) and then send me the node information (device settings > advanced > product ID/device ID/profile ID)?

**Comment by RobinBol** [comment]
I found the ids I need, will be added to a future beta release, please test and let me know if you have any issues (preferably via support@athom.com)!

**Comment by TerryBouhuizen** [comment]
Any idea when the beta will be released? For sure I will try!

    	
    	

    	Outlook voor iOS downloaden
    
  




On Mon, Sep 2, 2019 at 1:18 PM +0200, "Robin Bolscher" <notifications@github.com> wrote:












I found the ids I need, will be added to a future beta release, please test and let me know if you have any issues (preferably via support@athom.com)!

**Comment by TerryBouhuizen** [comment]
Because I cannot load the Alpha version (no idea why), when will the
Beta be online to install? 

Robin Bolscher schreef op 2019-09-02 13:17:

> Closed #75 [1]. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/athombv/com.ikea.tradfri/issues/75
[2]
https://github.com/athombv/com.ikea.tradfri/issues/75?email_source=notifications&amp;email_token=ANAGVB66S2OKA3ZSB5IZE3DQHTY6PA5CNFSM4IOZH6M2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTMCPQQI#event-2600794177
[3]
